article/urls.py
# 引入path
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # path函数将url映射到视图
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:article_id>', views.post_comment, name='post_comment'),
    path('post-comment/<int:article_id>/<int:parent_comment_id>/', views.post_comment, name='comment_reply'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

个人博客/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from article.views import article_list

urlpatterns = [
    path('', article_list, name='home'),

    path('admin/', admin.site.urls),

    path('article/', include('article.urls', namespace='article')),

    path('userprofile/', include('userprofile.urls', namespace='userprofile')),

    path('password-reset/', include('password_reset.urls')),

    path('comment/', include('comment.urls', namespace='comment')),

    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    path('notice/', include('notice.urls', namespace='notice')),

    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models

# Create your models here.
# 导入内建的User模型
from django.contrib.auth.models import User
# timezone用于处理时间相关事务
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from PIL import Image
from ckeditor.fields import RichTextField


# 文章栏目
class ArticleColumn(models.Model):

    title = models.CharField(max_length=100, blank=True)

    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


# 博客文章数据模型
class ArticlePost(models.Model):

    # 文章的栏目
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    # 文章标签
    tags = TaggableManager(blank=True)

    # 文章标题图
    avatar = models.ImageField(upload_to='article/%Y%m%d/', blank=True)

    # 文章作者，参数on_delete用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 文章标题。models.CharField为字符串字段，用于保存较短的字符串
    title = models.CharField(max_length=100)

    # 文章正文。保存大量文本使用TextField
    body = RichTextField()

    # 文章创建时间。参数 default=timezone.now 指定其在写入数据时默认写入当前时间
    created = models.DateTimeField(default=timezone.now())

    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)

    # 浏览量
    total_views = models.PositiveIntegerField(default=0)

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

    # 保存时处理图片
    def save(self, *args, **kwargs):
        # 调用原有的 save() 的功能
        article = super(ArticlePost, self).save(*args, **kwargs)

        # 固定宽度缩放图片大小
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            x, y = image.size()
            new_x = 480
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)
        return article

    # 内部类Meta用于给model定义元数据
    class Meta:
        # ordering指定模型返回的数据的排列顺序
        # '-created'表明数据应当以倒序排列
        ordering = ('-created',)

    # __str__定义当前对象调用str()方法时返回的内容
    def __str__(self):
        # 将文章的标题返回
        return self.title

article/forms.py
from django import forms
from .models import ArticlePost


# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body', 'tags', 'avatar')

article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ArticlePost, ArticleColumn
import markdown
from .forms import ArticlePostForm
from django.contrib.auth.admin import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment
from comment.forms import CommentForm


# 文章列表
def article_list(request):

    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    # 初始化查询集合
    article_list = ArticlePost.objects.all()

    if search:
        article_list = article_list.filter(
            Q(title__icontains=search)|
            Q(body__icontains=search)
        )
    else:
        search = ''

    # 栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

    # 标签查询集
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    # 查询集排序
    if order == 'total_views':
        article_list = article_list.order_by('-total_views')

    # 每页显示一篇文章
    paginator = Paginator(article_list, 3)
    # 获取URL中的页码
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给articles
    articles = paginator.get_page(page)

    # 需要传递给模板(templates)的对象
    context = {'articles': articles, 'order': order, 'search': search, 'column': column, 'tag': tag}
    # render函数，载入模板，并返回context对象
    return render(request, 'article/list.html', context)


# 文章详情
def article_detail(request, id):
    # 取出相应的文章
    article = ArticlePost.objects.get(id=id)

    # 取出相应评论
    comments = Comment.objects.filter(article=id)

    comment_form = CommentForm()

    # 浏览量+1
    article.total_views += 1
    article.save(update_fields=['total_views'])
    # 将markdown语法渲染成html样式
    md = markdown.Markdown(
        extensions=[
            # 包含缩写，表格等常用拓展
            'markdown.extensions.extra',
            # 语法高亮拓展
            'markdown.extensions.codehilite',
            # 目录拓展
            'markdown.extensions.toc',
        ])
    article.body = md.convert(article.body)

    # 需要传递给模板的对象
    context = {'article': article, 'toc': md.toc, 'comments': comments, 'comment_form': comment_form}
    # 载入模板，并返回context对象
    return render(request, 'article/detail.html', context)


# 写文章
@login_required(login_url='/userprofile/login/')
def article_create(request):
    # 判断用户请求类型
    if request.method == 'POST':
        # 将django表单类与数据进行绑定
        article_post_form = ArticlePostForm(request.POST, request.FILES)
        # 判断表单数据有效性(是否符合数据模型)
        if article_post_form.is_valid():
            # 若数据有效，则保存(commit=False表明先不提交到数据库)
            new_article = article_post_form.save(commit=False)
            # 获取作者信息
            new_article.author = User.objects.get(id=request.user.id)
            # 获取文章栏目信息
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            # 提交数据至数据库
            new_article.save()
            # 保存tags多对多关系
            article_post_form.save_m2m()
            # 重定向回文章列表页
            return redirect("article:article_list")
        else:
            return HttpResponse("表单内容有误，请重新填写")
    # 用户请求为GET的情况
    else:
        # 创建空的表单数据
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        # 将空表单数据返回
        context = {'article_post_form': article_post_form, 'columns': columns}
        return render(request, 'article/create.html', context)


# 删除文章
@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        # 根据id获取需要删除的文章
        article = ArticlePost.objects.get(id=id)

        if request.user != article.author:
            return HttpResponse("抱歉，您无权删除此文章")
        else:
            # 调用delete()方法删除
            article.delete()
            # 重定向回文章列表
            return redirect("article:article_list")

    else:
        return HttpResponse("仅允许POST请求")


# 修改文章
@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    # 提取需要修改的文章对象
    article = ArticlePost.objects.get(id=id)
    # 过滤非作者的用户
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改此文章")

    else:
        # 判断用户请求类型
        if request.method == 'POST':
            # 将提交的数据复制到表单实例中
            article_post_form = ArticlePostForm(data=request.POST)
            # 判断提交的数据的有效性
            if article_post_form.is_valid():
                # 将原文章的title、body和column用提交的内容替换
                article.title = request.POST['title']
                article.body = request.POST['body']
                if request.POST['column'] != 'none':
                    article.column = ArticleColumn.objects.get(id=request.POST['column'])
                else:
                    article.column = None
                if request.FILES.get('avatar'):
                    article.avatar = request.FILES.get('avatar')
                article.tags.set(*request.POST.get('tags').split(','), clear=True)
                article.save()
                # 重定向回该文章详情页
                return redirect("article:article_detail", id=id)
            else:
                return HttpResponse("表单内容有误，请重新填写")
        else:
            article_post_form = ArticlePostForm(initial={'body': article.body})
            columns = ArticleColumn.objects.all()
            tags = ','.join([x for x in article.tags.names()])
            # 赋值上下文，将article对象也传递进去，用以提取旧文章内容
            context = {'article': article, 'article_post_form': article_post_form, 'columns': columns, 'tags': tags}
            return render(request, 'article/update.html', context)

templates/article/create.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}写文章{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- 文章标题 -->
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <!-- 文章标题图 -->
                    <div class="form-group">
                        <label for="avatar">文章标题图</label>
                        <input type="file" class="form-control-file" id="avatar" name="avatar">
                    </div>
                    <!-- 文章栏目 -->
                    <div class="form-group">
                        <label for="column">文章栏目</label>
                        <select class="form-control" id="column" name="column">
                            <option value="none">请选择栏目...</option>
                            {% for column in columns %}
                                <option value="{{ column.id }}">{{ column }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <!-- 文章标签 -->
                    <div class="form-group">
                        <label for="tags">标签</label>
                        <input type="text" class="form-control col-3" id="tags" name="tags">
                    </div>
                    <!-- 文章正文 -->
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <div>
                            {{ article_post_form.media }}
                            {{ article_post_form.body }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    文章详情
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-9">
                <!-- 文章正文 -->
                <h1 class="col-12, mt-4, mb-4">{{ article.title }}</h1>
                <div class="col-12 alert alert-success">
                    <div>
                        作者: {{ article.author }}
                        {% if user == article.author %}
                            · <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                            · <a href="{% url 'article:article_update' article.id %}">编辑文章</a>
                        {% endif %}
                        <form
                            style="display:none"
                            id="safe_delete"
                            action="{% url 'article:article_safe_delete' article.id %}"
                            method="POST">
                        {% csrf_token %}
                        <button type="submit">发送</button>
                        </form>
                    </div>
                    <div>
                        浏览: {{ article.total_views }}
                    </div>
                </div>
                <div class="col-12">
                    <p>{{ article.body|safe }}</p>
                </div>
                <!-- 发表评论 -->
                <hr>
                {% if user.is_authenticated %}
                    <div>
                        <form
                            action="{% url 'comment:post_comment' article.id %}"
                            method="POST">
                            {% csrf_token %}
                                <div class="form-group">
                                    <label for="body"><strong>我也要发言：</strong></label>
                                    <div>
                                        {{ comment_form.media }}
                                        {{ comment_form.body }}
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">发送</button>
                        </form>
                    </div>
                    <br>
                {% else %}
                    <br>
                    <h5 class="row justify-content-center">
                    请<a href="{% url 'account_login' %}">登陆</a>后发表评论
                    </h5>
                    <br>
                {% endif %}
                <!-- 显示评论 -->
                {% load mptt_tags %}
                <h4>共有{{ comments.count }}条评论</h4>
                <div class="row">
                    <!-- 遍历树形结构 -->
                    {% recursetree comments %}
                        <!-- 给 node 取个别名 comment -->
                        {% with comment=node %}
                            <div class="{% if comment.reply_to %}
                                        offset-1 col-11
                                        {% else %}
                                        col-12
                                        {% endif %}" id="comment_elem_{{ comment.id }}"
                            >
                                <hr>
                                <p>
                                    <strong style="color: pink">
                                        {{ comment.user }}
                                    </strong>

                                    {% if comment.reply_to %}
                                        <i class="far fa-arrow-alt-circle-right"
                                           style="color: cornflowerblue;"
                                        ></i>
                                        <strong style="color: pink">
                                            {{ comment.reply_to }}
                                        </strong>
                                    {% endif %}

                                </p>
                                <div>{{ comment.body|safe }}</div>

                                <div>
                                    <span style="color: gray">
                                        {{ comment.created|date:"Y-m-d H:i" }}
                                    </span>

                                    <!-- 加载 modal 的按钮 -->
                                    {% if user.is_authenticated %}
                                    <button type="button"
                                            class="btn btn-light btn-sm text-muted"
                                            onclick="load_modal({{ article.id }}, {{ comment.id }})"
                                            >
                                        回复
                                    </button>
                                    {% else %}
                                    <a class="btn btn-light btn-sm text-muted"
                                       href="{% url 'userprofile:login' %}"
                                       >
                                        回复
                                    </a>
                                    {% endif %}
                                </div>

                                <!-- Modal -->
                                <div class="modal fade"
                                     id="comment_{{ comment.id }}"
                                     tabindex="-1"
                                     role="dialog"
                                     aria-labelledby="CommentModalCenter"
                                     aria-hidden="true"
                                >
                                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                        <div class="modal-content" style="height: 480px">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                                            </div>
                                            <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                        </div>

                                    </div>
                                </div>

                                {% if not comment.is_leaf_node %}
                                    <div class="children">
                                        {{ children }}
                                    </div>
                                {% endif %}
                            </div>


                        {% endwith %}
                    {% endrecursetree %}
                </div>
            </div>

            <!-- 目录 -->
            <div class="col-3 mt-4" id="sidebar" class="sidebar">
                <div class="sidebar__inner">
                    <h4><strong>目录</strong></h4>
                    <hr>
                    <div>
                        {{ toc|safe }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <style>
    .sidebar{
        will-change: min-height;
    }

    .sidebar__inner{
        transform: translate(0, 0);
        transform: translate3d(0, 0, 0);
        will-change: position, transform;
    }
    </style>

    {% block script %}
    <script>
        function confirm_safe_delete(){
            layer.open({
                title: "确认删除",
                content: "确认删除这篇文章吗？",
                yes: function(index, layero){
                    $('form#safe_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'prism/prism.css' %}">
    <script>
        $(".django-ckeditor-widget").removeAttr('style')
    </script>
    <script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
    <script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
    </script>
    <script>
       function load_modal(article_id, comment_id) {
            let modal_body = '#modal_body_' + comment_id;
            let modal_id = '#comment_' + comment_id;

            // 加载编辑器
            if ($(modal_body).children().length === 0) {
                let content = '<iframe src="/comment/post-comment/' +
                    article_id +
                    '/' +
                    comment_id +
                    '" frameborder="0" style="width: 100%; height: 100%;"></iframe>';
                $(modal_body).append(content);
            };

            $(modal_id).modal('show');
        }
    </script>
    <script>
        function post_reply_and_show_it(new_commend_id){
            let next_url = "{% url 'article:article_detail' article.id %}";
            // 去除URL尾部的'/'
            next_url = next_url.charAt(next_url.length - 1) == '/' ? next_url.slice(0, -1) : next_url;
            // 刷新并定位到锚点
            window.location.replace(next_url + "#comment_elem_" + new_commend_id)
        }
    </script>
    {% endblock script %}
{% endblock content %}

templates/article/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
首页
{% endblock title %}

{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'article:article_list' %}?search={{ search }}&column={{ column }}&tag={{ tag }}">
                        最新
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}&column={{ column }}&tag={{ tag }}">
                        最热
                    </a>
                </li>
            </ol>
        </nav>

        <!-- 搜索框 -->
        <div class="row">
            <div class="col-auto mr-auto">
                <form class="form-inline">
                    <label class="sr-only">content</label>
                    <input type="text" class="form-control mb-2 mr-sm-2"
                           name="search" placeholder="搜索文章..." required>
                </form>
            </div>
        </div>

        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章</h4>
                <hr>
            {% endif %}
        {% endif %}

        <div class="row mt-2">
            {% for article in articles %}
                <!-- 标题图 -->
                {% if article.avatar %}
                    <div class="col-3">
                        <img src="{{ article.avatar.url }}" alt="avatar" style="max-width:100%; border-radius:20px">
                    </div>
                {% endif %}
                <!-- 文章内容 -->
                <div class="col-12">
                    <!-- 栏目 -->
                    {% if article.column %}
                        <button type="button" class="btn btn-sm mb-2
                                {% if article.column.title == 'Django' %} btn-success
                                {% elif article.column.title == 'JAVA' %} btn-danger
                                {% elif article.column.title == 'HTML' %} btn-warning
                                {% endif %}">{{ article.column }}</button>
                    {% endif %}
                    <!-- 标签 -->
                    <span>
                        {% for tag in article.tags.all %}
                            <a href="{% url 'article:article_list' %}?tag={{ tag }}" class="badge badge-secondary">{{ tag }}</a>
                        {% endfor %}
                    </span>
                    <!-- 标题 -->
                    <h4>
                        <b>
                            <a href="{% url 'article:article_detail' article.id %}" style="color: black">
                                {{ article.title }}
                            </a>
                        </b>
                    </h4>
                    <!-- 摘要 -->
                    <div>
                        <p style="color: gray;">
                            {{ article.body|slice:'100' }}
                        </p>
                    </div>
                    <!-- 注脚 -->
                    <p>
                        <!-- 附加信息 -->
                        <span style="color: green">
                            {{ article.total_views }} 浏览&nbsp;&nbsp;&nbsp;
                        </span>
                        <span style="color: blue">
                            {{ article.created|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
                        </span>
                        <span style="color: darkred">
                            {{ article.updated|date:'Y-m-d' }}更新
                        </span>
                    </p>
                    <hr>
                </div>
            {% endfor %}
        </div>

        <!-- 页码导航 -->
        <div class="pagination row">
            <div class="m-auto">
                <span class="step-links">
                    <!-- 如果不是第一页，则显示上翻按钮 -->
                    {% if articles.has_previous %}
                        <a href="?page=1&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-success">
                             &laquo; 1
                        </a>
                        <span>...</span>
                        <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-secondary">
                            {{ articles.previous_page_number }}
                        </a>
                    {% endif %}

                    <!-- 当前页面 -->
                    <span class="current btn btn-danger">
                        {{ articles.number }}
                    </span>

                    <!-- 如果不是最后一页 则显示下翻按钮 -->
                    {% if articles.has_next %}
                        <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-secondary">
                            {{ articles.next_page_number }}
                        </a>
                        <span>...</span>
                        <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-success">
                            {{ articles.paginator.num_pages }} &raquo;
                        </a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock content %}

templates/article/update.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}更新文章{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="POST" action=".">
                    {% csrf_token %}
                    <!-- 文章标题 -->
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        <input type="text" class="form-control" id='title' name="title" value="{{ article.title }}"
                    </div>
                    <!-- 文章标题图 -->
                    <div class="form-group">
                        <label for="avatar">文章标题图</label>
                        <input type="file" class="form-control-file" id="avatar" name="avatar">
                    </div>
                    <!-- 文章栏目 -->
                    <div class="form-group">
                        <label for="column">文章栏目</label>
                        <select class="form-group" id="column" name="column">
                            <option value="none">请选择栏目...</option>
                            {% for column in columns %}
                                <option value="{{ column.id }}"
                                        {% if column.id == article.column.id %}
                                            selected
                                        {% endif %}>
                                    {{ column }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <!-- 文章标签 -->
                    <div class="form-group">
                        <label for="tags">文章标签</label>
                        <input type="text" class="form-control col-3" id="tags" name="tags" value="{{ tags }}">
                    </div>
                    <!-- 文章正文 -->
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <div>
                            {{ article_post_form.media }}
                            {{ article_post_form.body }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content%}